// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yarn_spinner.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package Yarn;

@kotlin.jvm.JvmName("-initializeheader")
public inline fun header(block: Yarn.HeaderKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Header =
  Yarn.HeaderKt.Dsl._create(Yarn.YarnSpinner.Header.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Yarn.Header`
 */
public object HeaderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Yarn.YarnSpinner.Header.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Yarn.YarnSpinner.Header.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Yarn.YarnSpinner.Header = _builder.build()

    /**
     * ```
     * The name of the header.
     * ```
     *
     * `string key = 1;`
     */
    public var key: kotlin.String
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * ```
     * The name of the header.
     * ```
     *
     * `string key = 1;`
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * ```
     * The value of the header.
     * ```
     *
     * `string value = 2;`
     */
    public var value: kotlin.String
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * ```
     * The value of the header.
     * ```
     *
     * `string value = 2;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Header.copy(block: `Yarn`.HeaderKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Header =
  `Yarn`.HeaderKt.Dsl._create(this.toBuilder()).apply { block() }._build()

