// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yarn_spinner.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package Yarn;

@kotlin.jvm.JvmName("-initializeinstructionV1")
public inline fun instructionV1(block: Yarn.InstructionV1Kt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.InstructionV1 =
  Yarn.InstructionV1Kt.Dsl._create(Yarn.YarnSpinner.InstructionV1.newBuilder()).apply { block() }._build()
/**
 * ```
 * A single Yarn instruction.
 * ```
 *
 * Protobuf type `Yarn.InstructionV1`
 */
public object InstructionV1Kt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Yarn.YarnSpinner.InstructionV1.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Yarn.YarnSpinner.InstructionV1.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Yarn.YarnSpinner.InstructionV1 = _builder.build()

    /**
     * ```
     * The operation that this instruction will perform.
     * ```
     *
     * `.Yarn.InstructionV1.OpCode opcode = 1;`
     */
    public var opcode: Yarn.YarnSpinner.InstructionV1.OpCode
      @kotlin.jvm.JvmName("getOpcode")
        get() = _builder.opcode
      @kotlin.jvm.JvmName("setOpcode")
        set(value) {
        _builder.opcode = value
      }
    public var opcodeValue: kotlin.Int
      @kotlin.jvm.JvmName("getOpcodeValue")
        get() = _builder.opcodeValue
      @kotlin.jvm.JvmName("setOpcodeValue")
        set(value) {
        _builder.opcodeValue = value
      }
    /**
     * ```
     * The operation that this instruction will perform.
     * ```
     *
     * `.Yarn.InstructionV1.OpCode opcode = 1;`
     */
    public fun clearOpcode() {
      _builder.clearOpcode()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OperandsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     */
     public val operands: com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.operandsList
      )
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     * @param value The operands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addOperands")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>.add(value: Yarn.YarnSpinner.Operand) {
      _builder.addOperands(value)
    }
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     * @param value The operands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignOperands")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>.plusAssign(value: Yarn.YarnSpinner.Operand) {
      add(value)
    }
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     * @param values The operands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllOperands")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>.addAll(values: kotlin.collections.Iterable<Yarn.YarnSpinner.Operand>) {
      _builder.addAllOperands(values)
    }
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     * @param values The operands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllOperands")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>.plusAssign(values: kotlin.collections.Iterable<Yarn.YarnSpinner.Operand>) {
      addAll(values)
    }
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     * @param index The index to set the value at.
     * @param value The operands to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOperands")
    public operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>.set(index: kotlin.Int, value: Yarn.YarnSpinner.Operand) {
      _builder.setOperands(index, value)
    }
    /**
     * ```
     * The list of operands, if any, that this instruction uses.
     * ```
     *
     * `repeated .Yarn.Operand operands = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearOperands")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Operand, OperandsProxy>.clear() {
      _builder.clearOperands()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.InstructionV1.copy(block: `Yarn`.InstructionV1Kt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.InstructionV1 =
  `Yarn`.InstructionV1Kt.Dsl._create(this.toBuilder()).apply { block() }._build()

