// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yarn_spinner.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package Yarn;

@kotlin.jvm.JvmName("-initializeinstruction")
public inline fun instruction(block: Yarn.InstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction =
  Yarn.InstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Yarn.Instruction`
 */
public object InstructionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Yarn.YarnSpinner.Instruction.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Yarn.YarnSpinner.Instruction.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Yarn.YarnSpinner.Instruction = _builder.build()

    /**
     * ```
     * Jumps to a specified position in the current node.
     * ```
     *
     * `.Yarn.Instruction.JumpToInstruction jumpTo = 1;`
     */
    public var jumpTo: Yarn.YarnSpinner.Instruction.JumpToInstruction
      @kotlin.jvm.JvmName("getJumpTo")
        get() = _builder.jumpTo
      @kotlin.jvm.JvmName("setJumpTo")
        set(value) {
        _builder.jumpTo = value
      }
    /**
     * ```
     * Jumps to a specified position in the current node.
     * ```
     *
     * `.Yarn.Instruction.JumpToInstruction jumpTo = 1;`
     */
    public fun clearJumpTo() {
      _builder.clearJumpTo()
    }
    /**
     * ```
     * Jumps to a specified position in the current node.
     * ```
     *
     * `.Yarn.Instruction.JumpToInstruction jumpTo = 1;`
     * @return Whether the jumpTo field is set.
     */
    public fun hasJumpTo(): kotlin.Boolean {
      return _builder.hasJumpTo()
    }

    /**
     * ```
     * Peeks a number on the stack, and jumps to that position in the
     * current node.
     * ```
     *
     * `.Yarn.Instruction.PeekAndJumpInstruction peekAndJump = 2;`
     */
    public var peekAndJump: Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction
      @kotlin.jvm.JvmName("getPeekAndJump")
        get() = _builder.peekAndJump
      @kotlin.jvm.JvmName("setPeekAndJump")
        set(value) {
        _builder.peekAndJump = value
      }
    /**
     * ```
     * Peeks a number on the stack, and jumps to that position in the
     * current node.
     * ```
     *
     * `.Yarn.Instruction.PeekAndJumpInstruction peekAndJump = 2;`
     */
    public fun clearPeekAndJump() {
      _builder.clearPeekAndJump()
    }
    /**
     * ```
     * Peeks a number on the stack, and jumps to that position in the
     * current node.
     * ```
     *
     * `.Yarn.Instruction.PeekAndJumpInstruction peekAndJump = 2;`
     * @return Whether the peekAndJump field is set.
     */
    public fun hasPeekAndJump(): kotlin.Boolean {
      return _builder.hasPeekAndJump()
    }

    /**
     * ```
     * Runs a line of dialogue.
     * ```
     *
     * `.Yarn.Instruction.RunLineInstruction runLine = 3;`
     */
    public var runLine: Yarn.YarnSpinner.Instruction.RunLineInstruction
      @kotlin.jvm.JvmName("getRunLine")
        get() = _builder.runLine
      @kotlin.jvm.JvmName("setRunLine")
        set(value) {
        _builder.runLine = value
      }
    /**
     * ```
     * Runs a line of dialogue.
     * ```
     *
     * `.Yarn.Instruction.RunLineInstruction runLine = 3;`
     */
    public fun clearRunLine() {
      _builder.clearRunLine()
    }
    /**
     * ```
     * Runs a line of dialogue.
     * ```
     *
     * `.Yarn.Instruction.RunLineInstruction runLine = 3;`
     * @return Whether the runLine field is set.
     */
    public fun hasRunLine(): kotlin.Boolean {
      return _builder.hasRunLine()
    }

    /**
     * ```
     * Runs a command.
     * ```
     *
     * `.Yarn.Instruction.RunCommandInstruction runCommand = 4;`
     */
    public var runCommand: Yarn.YarnSpinner.Instruction.RunCommandInstruction
      @kotlin.jvm.JvmName("getRunCommand")
        get() = _builder.runCommand
      @kotlin.jvm.JvmName("setRunCommand")
        set(value) {
        _builder.runCommand = value
      }
    /**
     * ```
     * Runs a command.
     * ```
     *
     * `.Yarn.Instruction.RunCommandInstruction runCommand = 4;`
     */
    public fun clearRunCommand() {
      _builder.clearRunCommand()
    }
    /**
     * ```
     * Runs a command.
     * ```
     *
     * `.Yarn.Instruction.RunCommandInstruction runCommand = 4;`
     * @return Whether the runCommand field is set.
     */
    public fun hasRunCommand(): kotlin.Boolean {
      return _builder.hasRunCommand()
    }

    /**
     * ```
     * Adds an option to the 'pending options' list.
     * ```
     *
     * `.Yarn.Instruction.AddOptionInstruction addOption = 5;`
     */
    public var addOption: Yarn.YarnSpinner.Instruction.AddOptionInstruction
      @kotlin.jvm.JvmName("getAddOption")
        get() = _builder.addOption
      @kotlin.jvm.JvmName("setAddOption")
        set(value) {
        _builder.addOption = value
      }
    /**
     * ```
     * Adds an option to the 'pending options' list.
     * ```
     *
     * `.Yarn.Instruction.AddOptionInstruction addOption = 5;`
     */
    public fun clearAddOption() {
      _builder.clearAddOption()
    }
    /**
     * ```
     * Adds an option to the 'pending options' list.
     * ```
     *
     * `.Yarn.Instruction.AddOptionInstruction addOption = 5;`
     * @return Whether the addOption field is set.
     */
    public fun hasAddOption(): kotlin.Boolean {
      return _builder.hasAddOption()
    }

    /**
     * ```
     * Shows all options in the 'pending options' list, then clears the list.
     * ```
     *
     * `.Yarn.Instruction.ShowOptionsInstruction showOptions = 6;`
     */
    public var showOptions: Yarn.YarnSpinner.Instruction.ShowOptionsInstruction
      @kotlin.jvm.JvmName("getShowOptions")
        get() = _builder.showOptions
      @kotlin.jvm.JvmName("setShowOptions")
        set(value) {
        _builder.showOptions = value
      }
    /**
     * ```
     * Shows all options in the 'pending options' list, then clears the list.
     * ```
     *
     * `.Yarn.Instruction.ShowOptionsInstruction showOptions = 6;`
     */
    public fun clearShowOptions() {
      _builder.clearShowOptions()
    }
    /**
     * ```
     * Shows all options in the 'pending options' list, then clears the list.
     * ```
     *
     * `.Yarn.Instruction.ShowOptionsInstruction showOptions = 6;`
     * @return Whether the showOptions field is set.
     */
    public fun hasShowOptions(): kotlin.Boolean {
      return _builder.hasShowOptions()
    }

    /**
     * ```
     * Pushes a string onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushStringInstruction pushString = 7;`
     */
    public var pushString: Yarn.YarnSpinner.Instruction.PushStringInstruction
      @kotlin.jvm.JvmName("getPushString")
        get() = _builder.pushString
      @kotlin.jvm.JvmName("setPushString")
        set(value) {
        _builder.pushString = value
      }
    /**
     * ```
     * Pushes a string onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushStringInstruction pushString = 7;`
     */
    public fun clearPushString() {
      _builder.clearPushString()
    }
    /**
     * ```
     * Pushes a string onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushStringInstruction pushString = 7;`
     * @return Whether the pushString field is set.
     */
    public fun hasPushString(): kotlin.Boolean {
      return _builder.hasPushString()
    }

    /**
     * ```
     * Pushes a floating point number onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushFloatInstruction pushFloat = 8;`
     */
    public var pushFloat: Yarn.YarnSpinner.Instruction.PushFloatInstruction
      @kotlin.jvm.JvmName("getPushFloat")
        get() = _builder.pushFloat
      @kotlin.jvm.JvmName("setPushFloat")
        set(value) {
        _builder.pushFloat = value
      }
    /**
     * ```
     * Pushes a floating point number onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushFloatInstruction pushFloat = 8;`
     */
    public fun clearPushFloat() {
      _builder.clearPushFloat()
    }
    /**
     * ```
     * Pushes a floating point number onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushFloatInstruction pushFloat = 8;`
     * @return Whether the pushFloat field is set.
     */
    public fun hasPushFloat(): kotlin.Boolean {
      return _builder.hasPushFloat()
    }

    /**
     * ```
     * Pushes a boolean onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushBoolInstruction pushBool = 9;`
     */
    public var pushBool: Yarn.YarnSpinner.Instruction.PushBoolInstruction
      @kotlin.jvm.JvmName("getPushBool")
        get() = _builder.pushBool
      @kotlin.jvm.JvmName("setPushBool")
        set(value) {
        _builder.pushBool = value
      }
    /**
     * ```
     * Pushes a boolean onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushBoolInstruction pushBool = 9;`
     */
    public fun clearPushBool() {
      _builder.clearPushBool()
    }
    /**
     * ```
     * Pushes a boolean onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushBoolInstruction pushBool = 9;`
     * @return Whether the pushBool field is set.
     */
    public fun hasPushBool(): kotlin.Boolean {
      return _builder.hasPushBool()
    }

    /**
     * ```
     * Peeks a boolean on the stack, and if it's false, jumps to the
     * indicated position in the current node.
     * ```
     *
     * `.Yarn.Instruction.JumpIfFalseInstruction jumpIfFalse = 10;`
     */
    public var jumpIfFalse: Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction
      @kotlin.jvm.JvmName("getJumpIfFalse")
        get() = _builder.jumpIfFalse
      @kotlin.jvm.JvmName("setJumpIfFalse")
        set(value) {
        _builder.jumpIfFalse = value
      }
    /**
     * ```
     * Peeks a boolean on the stack, and if it's false, jumps to the
     * indicated position in the current node.
     * ```
     *
     * `.Yarn.Instruction.JumpIfFalseInstruction jumpIfFalse = 10;`
     */
    public fun clearJumpIfFalse() {
      _builder.clearJumpIfFalse()
    }
    /**
     * ```
     * Peeks a boolean on the stack, and if it's false, jumps to the
     * indicated position in the current node.
     * ```
     *
     * `.Yarn.Instruction.JumpIfFalseInstruction jumpIfFalse = 10;`
     * @return Whether the jumpIfFalse field is set.
     */
    public fun hasJumpIfFalse(): kotlin.Boolean {
      return _builder.hasJumpIfFalse()
    }

    /**
     * ```
     * Pops a value of any kind off the stack.
     * ```
     *
     * `.Yarn.Instruction.PopInstruction pop = 11;`
     */
    public var pop: Yarn.YarnSpinner.Instruction.PopInstruction
      @kotlin.jvm.JvmName("getPop")
        get() = _builder.pop
      @kotlin.jvm.JvmName("setPop")
        set(value) {
        _builder.pop = value
      }
    /**
     * ```
     * Pops a value of any kind off the stack.
     * ```
     *
     * `.Yarn.Instruction.PopInstruction pop = 11;`
     */
    public fun clearPop() {
      _builder.clearPop()
    }
    /**
     * ```
     * Pops a value of any kind off the stack.
     * ```
     *
     * `.Yarn.Instruction.PopInstruction pop = 11;`
     * @return Whether the pop field is set.
     */
    public fun hasPop(): kotlin.Boolean {
      return _builder.hasPop()
    }

    /**
     * ```
     * Calls a named function.
     * ```
     *
     * `.Yarn.Instruction.CallFunctionInstruction callFunc = 12;`
     */
    public var callFunc: Yarn.YarnSpinner.Instruction.CallFunctionInstruction
      @kotlin.jvm.JvmName("getCallFunc")
        get() = _builder.callFunc
      @kotlin.jvm.JvmName("setCallFunc")
        set(value) {
        _builder.callFunc = value
      }
    /**
     * ```
     * Calls a named function.
     * ```
     *
     * `.Yarn.Instruction.CallFunctionInstruction callFunc = 12;`
     */
    public fun clearCallFunc() {
      _builder.clearCallFunc()
    }
    /**
     * ```
     * Calls a named function.
     * ```
     *
     * `.Yarn.Instruction.CallFunctionInstruction callFunc = 12;`
     * @return Whether the callFunc field is set.
     */
    public fun hasCallFunc(): kotlin.Boolean {
      return _builder.hasCallFunc()
    }

    /**
     * ```
     * Pushes the value of the named variable onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushVariableInstruction pushVariable = 13;`
     */
    public var pushVariable: Yarn.YarnSpinner.Instruction.PushVariableInstruction
      @kotlin.jvm.JvmName("getPushVariable")
        get() = _builder.pushVariable
      @kotlin.jvm.JvmName("setPushVariable")
        set(value) {
        _builder.pushVariable = value
      }
    /**
     * ```
     * Pushes the value of the named variable onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushVariableInstruction pushVariable = 13;`
     */
    public fun clearPushVariable() {
      _builder.clearPushVariable()
    }
    /**
     * ```
     * Pushes the value of the named variable onto the stack.
     * ```
     *
     * `.Yarn.Instruction.PushVariableInstruction pushVariable = 13;`
     * @return Whether the pushVariable field is set.
     */
    public fun hasPushVariable(): kotlin.Boolean {
      return _builder.hasPushVariable()
    }

    /**
     * ```
     * Peeks a value of any kind on the stack, and stores it in the
     * indicated variable.
     * ```
     *
     * `.Yarn.Instruction.StoreVariableInstruction storeVariable = 14;`
     */
    public var storeVariable: Yarn.YarnSpinner.Instruction.StoreVariableInstruction
      @kotlin.jvm.JvmName("getStoreVariable")
        get() = _builder.storeVariable
      @kotlin.jvm.JvmName("setStoreVariable")
        set(value) {
        _builder.storeVariable = value
      }
    /**
     * ```
     * Peeks a value of any kind on the stack, and stores it in the
     * indicated variable.
     * ```
     *
     * `.Yarn.Instruction.StoreVariableInstruction storeVariable = 14;`
     */
    public fun clearStoreVariable() {
      _builder.clearStoreVariable()
    }
    /**
     * ```
     * Peeks a value of any kind on the stack, and stores it in the
     * indicated variable.
     * ```
     *
     * `.Yarn.Instruction.StoreVariableInstruction storeVariable = 14;`
     * @return Whether the storeVariable field is set.
     */
    public fun hasStoreVariable(): kotlin.Boolean {
      return _builder.hasStoreVariable()
    }

    /**
     * ```
     * Halts execution.
     * ```
     *
     * `.Yarn.Instruction.StopInstruction stop = 15;`
     */
    public var stop: Yarn.YarnSpinner.Instruction.StopInstruction
      @kotlin.jvm.JvmName("getStop")
        get() = _builder.stop
      @kotlin.jvm.JvmName("setStop")
        set(value) {
        _builder.stop = value
      }
    /**
     * ```
     * Halts execution.
     * ```
     *
     * `.Yarn.Instruction.StopInstruction stop = 15;`
     */
    public fun clearStop() {
      _builder.clearStop()
    }
    /**
     * ```
     * Halts execution.
     * ```
     *
     * `.Yarn.Instruction.StopInstruction stop = 15;`
     * @return Whether the stop field is set.
     */
    public fun hasStop(): kotlin.Boolean {
      return _builder.hasStop()
    }

    /**
     * ```
     * Jumps to the start of a named node.
     * ```
     *
     * `.Yarn.Instruction.RunNodeInstruction runNode = 16;`
     */
    public var runNode: Yarn.YarnSpinner.Instruction.RunNodeInstruction
      @kotlin.jvm.JvmName("getRunNode")
        get() = _builder.runNode
      @kotlin.jvm.JvmName("setRunNode")
        set(value) {
        _builder.runNode = value
      }
    /**
     * ```
     * Jumps to the start of a named node.
     * ```
     *
     * `.Yarn.Instruction.RunNodeInstruction runNode = 16;`
     */
    public fun clearRunNode() {
      _builder.clearRunNode()
    }
    /**
     * ```
     * Jumps to the start of a named node.
     * ```
     *
     * `.Yarn.Instruction.RunNodeInstruction runNode = 16;`
     * @return Whether the runNode field is set.
     */
    public fun hasRunNode(): kotlin.Boolean {
      return _builder.hasRunNode()
    }

    /**
     * ```
     * Peeks a string on the stack, and jumps to the start of that node.
     * ```
     *
     * `.Yarn.Instruction.PeekAndRunNodeInstruction peekAndRunNode = 17;`
     */
    public var peekAndRunNode: Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction
      @kotlin.jvm.JvmName("getPeekAndRunNode")
        get() = _builder.peekAndRunNode
      @kotlin.jvm.JvmName("setPeekAndRunNode")
        set(value) {
        _builder.peekAndRunNode = value
      }
    /**
     * ```
     * Peeks a string on the stack, and jumps to the start of that node.
     * ```
     *
     * `.Yarn.Instruction.PeekAndRunNodeInstruction peekAndRunNode = 17;`
     */
    public fun clearPeekAndRunNode() {
      _builder.clearPeekAndRunNode()
    }
    /**
     * ```
     * Peeks a string on the stack, and jumps to the start of that node.
     * ```
     *
     * `.Yarn.Instruction.PeekAndRunNodeInstruction peekAndRunNode = 17;`
     * @return Whether the peekAndRunNode field is set.
     */
    public fun hasPeekAndRunNode(): kotlin.Boolean {
      return _builder.hasPeekAndRunNode()
    }

    /**
     * `.Yarn.Instruction.DetourToNodeInstruction detourToNode = 18;`
     */
    public var detourToNode: Yarn.YarnSpinner.Instruction.DetourToNodeInstruction
      @kotlin.jvm.JvmName("getDetourToNode")
        get() = _builder.detourToNode
      @kotlin.jvm.JvmName("setDetourToNode")
        set(value) {
        _builder.detourToNode = value
      }
    /**
     * `.Yarn.Instruction.DetourToNodeInstruction detourToNode = 18;`
     */
    public fun clearDetourToNode() {
      _builder.clearDetourToNode()
    }
    /**
     * `.Yarn.Instruction.DetourToNodeInstruction detourToNode = 18;`
     * @return Whether the detourToNode field is set.
     */
    public fun hasDetourToNode(): kotlin.Boolean {
      return _builder.hasDetourToNode()
    }

    /**
     * `.Yarn.Instruction.PeekAndDetourToNode peekAndDetourToNode = 19;`
     */
    public var peekAndDetourToNode: Yarn.YarnSpinner.Instruction.PeekAndDetourToNode
      @kotlin.jvm.JvmName("getPeekAndDetourToNode")
        get() = _builder.peekAndDetourToNode
      @kotlin.jvm.JvmName("setPeekAndDetourToNode")
        set(value) {
        _builder.peekAndDetourToNode = value
      }
    /**
     * `.Yarn.Instruction.PeekAndDetourToNode peekAndDetourToNode = 19;`
     */
    public fun clearPeekAndDetourToNode() {
      _builder.clearPeekAndDetourToNode()
    }
    /**
     * `.Yarn.Instruction.PeekAndDetourToNode peekAndDetourToNode = 19;`
     * @return Whether the peekAndDetourToNode field is set.
     */
    public fun hasPeekAndDetourToNode(): kotlin.Boolean {
      return _builder.hasPeekAndDetourToNode()
    }

    /**
     * `.Yarn.Instruction.ReturnInstruction return = 20;`
     */
    public var return_: Yarn.YarnSpinner.Instruction.ReturnInstruction
      @kotlin.jvm.JvmName("getReturn_")
        get() = _builder.`return`
      @kotlin.jvm.JvmName("setReturn_")
        set(value) {
        _builder.`return` = value
      }
    /**
     * `.Yarn.Instruction.ReturnInstruction return = 20;`
     */
    public fun clearReturn_() {
      _builder.clearReturn()
    }
    /**
     * `.Yarn.Instruction.ReturnInstruction return = 20;`
     * @return Whether the return field is set.
     */
    public fun hasReturn_(): kotlin.Boolean {
      return _builder.hasReturn()
    }

    /**
     * ```
     * Pops a boolean from the stack, and adds a saliency candidate to the
     * current list.
     * ```
     *
     * `.Yarn.Instruction.AddSaliencyCandidateInstruction addSaliencyCandidate = 21;`
     */
    public var addSaliencyCandidate: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction
      @kotlin.jvm.JvmName("getAddSaliencyCandidate")
        get() = _builder.addSaliencyCandidate
      @kotlin.jvm.JvmName("setAddSaliencyCandidate")
        set(value) {
        _builder.addSaliencyCandidate = value
      }
    /**
     * ```
     * Pops a boolean from the stack, and adds a saliency candidate to the
     * current list.
     * ```
     *
     * `.Yarn.Instruction.AddSaliencyCandidateInstruction addSaliencyCandidate = 21;`
     */
    public fun clearAddSaliencyCandidate() {
      _builder.clearAddSaliencyCandidate()
    }
    /**
     * ```
     * Pops a boolean from the stack, and adds a saliency candidate to the
     * current list.
     * ```
     *
     * `.Yarn.Instruction.AddSaliencyCandidateInstruction addSaliencyCandidate = 21;`
     * @return Whether the addSaliencyCandidate field is set.
     */
    public fun hasAddSaliencyCandidate(): kotlin.Boolean {
      return _builder.hasAddSaliencyCandidate()
    }

    /**
     * ```
     * Add a saliency candidate to the current list, given a node name.
     * ```
     *
     * `.Yarn.Instruction.AddSaliencyCandidateFromNodeInstruction addSaliencyCandidateFromNode = 22;`
     */
    public var addSaliencyCandidateFromNode: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction
      @kotlin.jvm.JvmName("getAddSaliencyCandidateFromNode")
        get() = _builder.addSaliencyCandidateFromNode
      @kotlin.jvm.JvmName("setAddSaliencyCandidateFromNode")
        set(value) {
        _builder.addSaliencyCandidateFromNode = value
      }
    /**
     * ```
     * Add a saliency candidate to the current list, given a node name.
     * ```
     *
     * `.Yarn.Instruction.AddSaliencyCandidateFromNodeInstruction addSaliencyCandidateFromNode = 22;`
     */
    public fun clearAddSaliencyCandidateFromNode() {
      _builder.clearAddSaliencyCandidateFromNode()
    }
    /**
     * ```
     * Add a saliency candidate to the current list, given a node name.
     * ```
     *
     * `.Yarn.Instruction.AddSaliencyCandidateFromNodeInstruction addSaliencyCandidateFromNode = 22;`
     * @return Whether the addSaliencyCandidateFromNode field is set.
     */
    public fun hasAddSaliencyCandidateFromNode(): kotlin.Boolean {
      return _builder.hasAddSaliencyCandidateFromNode()
    }

    /**
     * ```
     * Attempt to select a single saliency candidate from the current list:
     * - if one is selected, pushes the destination of that candidate and
     * the value 'true'
     * - if none is selected, pushes the value 'false'
     *
     * In all circumstances, clears the saliency candidate list before
     * returning.
     * ```
     *
     * `.Yarn.Instruction.SelectSaliencyCandidateInstruction selectSaliencyCandidate = 23;`
     */
    public var selectSaliencyCandidate: Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction
      @kotlin.jvm.JvmName("getSelectSaliencyCandidate")
        get() = _builder.selectSaliencyCandidate
      @kotlin.jvm.JvmName("setSelectSaliencyCandidate")
        set(value) {
        _builder.selectSaliencyCandidate = value
      }
    /**
     * ```
     * Attempt to select a single saliency candidate from the current list:
     * - if one is selected, pushes the destination of that candidate and
     * the value 'true'
     * - if none is selected, pushes the value 'false'
     *
     * In all circumstances, clears the saliency candidate list before
     * returning.
     * ```
     *
     * `.Yarn.Instruction.SelectSaliencyCandidateInstruction selectSaliencyCandidate = 23;`
     */
    public fun clearSelectSaliencyCandidate() {
      _builder.clearSelectSaliencyCandidate()
    }
    /**
     * ```
     * Attempt to select a single saliency candidate from the current list:
     * - if one is selected, pushes the destination of that candidate and
     * the value 'true'
     * - if none is selected, pushes the value 'false'
     *
     * In all circumstances, clears the saliency candidate list before
     * returning.
     * ```
     *
     * `.Yarn.Instruction.SelectSaliencyCandidateInstruction selectSaliencyCandidate = 23;`
     * @return Whether the selectSaliencyCandidate field is set.
     */
    public fun hasSelectSaliencyCandidate(): kotlin.Boolean {
      return _builder.hasSelectSaliencyCandidate()
    }
    public val instructionTypeCase: Yarn.YarnSpinner.Instruction.InstructionTypeCase
    @kotlin.jvm.JvmName("getInstructionTypeCase")
      get() = _builder.getInstructionTypeCase()

    public fun clearInstructionType() {
      _builder.clearInstructionType()
    }
  }
  @kotlin.jvm.JvmName("-initializepeekAndJumpInstruction")
  public inline fun peekAndJumpInstruction(block: Yarn.InstructionKt.PeekAndJumpInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction =
    Yarn.InstructionKt.PeekAndJumpInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PeekAndJumpInstruction`
   */
  public object PeekAndJumpInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializepeekAndRunNodeInstruction")
  public inline fun peekAndRunNodeInstruction(block: Yarn.InstructionKt.PeekAndRunNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction =
    Yarn.InstructionKt.PeekAndRunNodeInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PeekAndRunNodeInstruction`
   */
  public object PeekAndRunNodeInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializeshowOptionsInstruction")
  public inline fun showOptionsInstruction(block: Yarn.InstructionKt.ShowOptionsInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.ShowOptionsInstruction =
    Yarn.InstructionKt.ShowOptionsInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.ShowOptionsInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.ShowOptionsInstruction`
   */
  public object ShowOptionsInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.ShowOptionsInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.ShowOptionsInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.ShowOptionsInstruction = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializepushStringInstruction")
  public inline fun pushStringInstruction(block: Yarn.InstructionKt.PushStringInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushStringInstruction =
    Yarn.InstructionKt.PushStringInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PushStringInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PushStringInstruction`
   */
  public object PushStringInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PushStringInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PushStringInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PushStringInstruction = _builder.build()

      /**
       * ```
       * The value to push.
       * ```
       *
       * `string value = 1;`
       */
      public var value: kotlin.String
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * ```
       * The value to push.
       * ```
       *
       * `string value = 1;`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializepushFloatInstruction")
  public inline fun pushFloatInstruction(block: Yarn.InstructionKt.PushFloatInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushFloatInstruction =
    Yarn.InstructionKt.PushFloatInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PushFloatInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PushFloatInstruction`
   */
  public object PushFloatInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PushFloatInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PushFloatInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PushFloatInstruction = _builder.build()

      /**
       * ```
       * The value to push.
       * ```
       *
       * `float value = 1;`
       */
      public var value: kotlin.Float
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * ```
       * The value to push.
       * ```
       *
       * `float value = 1;`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializepushBoolInstruction")
  public inline fun pushBoolInstruction(block: Yarn.InstructionKt.PushBoolInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushBoolInstruction =
    Yarn.InstructionKt.PushBoolInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PushBoolInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PushBoolInstruction`
   */
  public object PushBoolInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PushBoolInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PushBoolInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PushBoolInstruction = _builder.build()

      /**
       * ```
       * The value to push.
       * ```
       *
       * `bool value = 1;`
       */
      public var value: kotlin.Boolean
        @kotlin.jvm.JvmName("getValue")
          get() = _builder.value
        @kotlin.jvm.JvmName("setValue")
          set(value) {
          _builder.value = value
        }
      /**
       * ```
       * The value to push.
       * ```
       *
       * `bool value = 1;`
       */
      public fun clearValue() {
        _builder.clearValue()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializejumpToInstruction")
  public inline fun jumpToInstruction(block: Yarn.InstructionKt.JumpToInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.JumpToInstruction =
    Yarn.InstructionKt.JumpToInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.JumpToInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.JumpToInstruction`
   */
  public object JumpToInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.JumpToInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.JumpToInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.JumpToInstruction = _builder.build()

      /**
       * ```
       * The instruction number in the current node to jump to.
       * ```
       *
       * `int32 destination = 1;`
       */
      public var destination: kotlin.Int
        @kotlin.jvm.JvmName("getDestination")
          get() = _builder.destination
        @kotlin.jvm.JvmName("setDestination")
          set(value) {
          _builder.destination = value
        }
      /**
       * ```
       * The instruction number in the current node to jump to.
       * ```
       *
       * `int32 destination = 1;`
       */
      public fun clearDestination() {
        _builder.clearDestination()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializerunLineInstruction")
  public inline fun runLineInstruction(block: Yarn.InstructionKt.RunLineInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.RunLineInstruction =
    Yarn.InstructionKt.RunLineInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.RunLineInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.RunLineInstruction`
   */
  public object RunLineInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.RunLineInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.RunLineInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.RunLineInstruction = _builder.build()

      /**
       * ```
       * The ID of the localised content that should be shown for this line.
       * ```
       *
       * `string lineID = 1;`
       */
      public var lineID: kotlin.String
        @kotlin.jvm.JvmName("getLineID")
          get() = _builder.lineID
        @kotlin.jvm.JvmName("setLineID")
          set(value) {
          _builder.lineID = value
        }
      /**
       * ```
       * The ID of the localised content that should be shown for this line.
       * ```
       *
       * `string lineID = 1;`
       */
      public fun clearLineID() {
        _builder.clearLineID()
      }

      /**
       * ```
       * The number of substitutions present in this line that must be popped
       * off the stack.
       * ```
       *
       * `int32 substitutionCount = 2;`
       */
      public var substitutionCount: kotlin.Int
        @kotlin.jvm.JvmName("getSubstitutionCount")
          get() = _builder.substitutionCount
        @kotlin.jvm.JvmName("setSubstitutionCount")
          set(value) {
          _builder.substitutionCount = value
        }
      /**
       * ```
       * The number of substitutions present in this line that must be popped
       * off the stack.
       * ```
       *
       * `int32 substitutionCount = 2;`
       */
      public fun clearSubstitutionCount() {
        _builder.clearSubstitutionCount()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializerunCommandInstruction")
  public inline fun runCommandInstruction(block: Yarn.InstructionKt.RunCommandInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.RunCommandInstruction =
    Yarn.InstructionKt.RunCommandInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.RunCommandInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.RunCommandInstruction`
   */
  public object RunCommandInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.RunCommandInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.RunCommandInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.RunCommandInstruction = _builder.build()

      /**
       * ```
       * The text of the command to send to the client.
       * ```
       *
       * `string commandText = 1;`
       */
      public var commandText: kotlin.String
        @kotlin.jvm.JvmName("getCommandText")
          get() = _builder.commandText
        @kotlin.jvm.JvmName("setCommandText")
          set(value) {
          _builder.commandText = value
        }
      /**
       * ```
       * The text of the command to send to the client.
       * ```
       *
       * `string commandText = 1;`
       */
      public fun clearCommandText() {
        _builder.clearCommandText()
      }

      /**
       * ```
       * The number of substitutions present in this command that must be popped
       * off the stack.
       * ```
       *
       * `int32 substitutionCount = 2;`
       */
      public var substitutionCount: kotlin.Int
        @kotlin.jvm.JvmName("getSubstitutionCount")
          get() = _builder.substitutionCount
        @kotlin.jvm.JvmName("setSubstitutionCount")
          set(value) {
          _builder.substitutionCount = value
        }
      /**
       * ```
       * The number of substitutions present in this command that must be popped
       * off the stack.
       * ```
       *
       * `int32 substitutionCount = 2;`
       */
      public fun clearSubstitutionCount() {
        _builder.clearSubstitutionCount()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeaddOptionInstruction")
  public inline fun addOptionInstruction(block: Yarn.InstructionKt.AddOptionInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.AddOptionInstruction =
    Yarn.InstructionKt.AddOptionInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.AddOptionInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.AddOptionInstruction`
   */
  public object AddOptionInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.AddOptionInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.AddOptionInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.AddOptionInstruction = _builder.build()

      /**
       * ```
       * The ID of the content that should be shown for this option.
       * ```
       *
       * `string lineID = 1;`
       */
      public var lineID: kotlin.String
        @kotlin.jvm.JvmName("getLineID")
          get() = _builder.lineID
        @kotlin.jvm.JvmName("setLineID")
          set(value) {
          _builder.lineID = value
        }
      /**
       * ```
       * The ID of the content that should be shown for this option.
       * ```
       *
       * `string lineID = 1;`
       */
      public fun clearLineID() {
        _builder.clearLineID()
      }

      /**
       * ```
       * The instruction number in the current node to jump to if this option
       * is selected.
       * ```
       *
       * `int32 destination = 2;`
       */
      public var destination: kotlin.Int
        @kotlin.jvm.JvmName("getDestination")
          get() = _builder.destination
        @kotlin.jvm.JvmName("setDestination")
          set(value) {
          _builder.destination = value
        }
      /**
       * ```
       * The instruction number in the current node to jump to if this option
       * is selected.
       * ```
       *
       * `int32 destination = 2;`
       */
      public fun clearDestination() {
        _builder.clearDestination()
      }

      /**
       * ```
       * The number of substitutions present in this option that must be popped
       * off the stack.
       * ```
       *
       * `int32 substitutionCount = 3;`
       */
      public var substitutionCount: kotlin.Int
        @kotlin.jvm.JvmName("getSubstitutionCount")
          get() = _builder.substitutionCount
        @kotlin.jvm.JvmName("setSubstitutionCount")
          set(value) {
          _builder.substitutionCount = value
        }
      /**
       * ```
       * The number of substitutions present in this option that must be popped
       * off the stack.
       * ```
       *
       * `int32 substitutionCount = 3;`
       */
      public fun clearSubstitutionCount() {
        _builder.clearSubstitutionCount()
      }

      /**
       * ```
       * A value indicating whether this instruction has a line condition on
       * it, whose evaluated value must be popped off the stack.
       * ```
       *
       * `bool hasCondition = 4;`
       */
      public var hasCondition: kotlin.Boolean
        @kotlin.jvm.JvmName("getHasCondition")
          get() = _builder.hasCondition
        @kotlin.jvm.JvmName("setHasCondition")
          set(value) {
          _builder.hasCondition = value
        }
      /**
       * ```
       * A value indicating whether this instruction has a line condition on
       * it, whose evaluated value must be popped off the stack.
       * ```
       *
       * `bool hasCondition = 4;`
       */
      public fun clearHasCondition() {
        _builder.clearHasCondition()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializejumpIfFalseInstruction")
  public inline fun jumpIfFalseInstruction(block: Yarn.InstructionKt.JumpIfFalseInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction =
    Yarn.InstructionKt.JumpIfFalseInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.JumpIfFalseInstruction`
   */
  public object JumpIfFalseInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction = _builder.build()

      /**
       * ```
       * The instruction number in the current node to jump to.
       * ```
       *
       * `int32 destination = 1;`
       */
      public var destination: kotlin.Int
        @kotlin.jvm.JvmName("getDestination")
          get() = _builder.destination
        @kotlin.jvm.JvmName("setDestination")
          set(value) {
          _builder.destination = value
        }
      /**
       * ```
       * The instruction number in the current node to jump to.
       * ```
       *
       * `int32 destination = 1;`
       */
      public fun clearDestination() {
        _builder.clearDestination()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializepopInstruction")
  public inline fun popInstruction(block: Yarn.InstructionKt.PopInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PopInstruction =
    Yarn.InstructionKt.PopInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PopInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PopInstruction`
   */
  public object PopInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PopInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PopInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PopInstruction = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializecallFunctionInstruction")
  public inline fun callFunctionInstruction(block: Yarn.InstructionKt.CallFunctionInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.CallFunctionInstruction =
    Yarn.InstructionKt.CallFunctionInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.CallFunctionInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.CallFunctionInstruction`
   */
  public object CallFunctionInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.CallFunctionInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.CallFunctionInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.CallFunctionInstruction = _builder.build()

      /**
       * ```
       * The name of the function to call.
       * ```
       *
       * `string functionName = 1;`
       */
      public var functionName: kotlin.String
        @kotlin.jvm.JvmName("getFunctionName")
          get() = _builder.functionName
        @kotlin.jvm.JvmName("setFunctionName")
          set(value) {
          _builder.functionName = value
        }
      /**
       * ```
       * The name of the function to call.
       * ```
       *
       * `string functionName = 1;`
       */
      public fun clearFunctionName() {
        _builder.clearFunctionName()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializepushVariableInstruction")
  public inline fun pushVariableInstruction(block: Yarn.InstructionKt.PushVariableInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushVariableInstruction =
    Yarn.InstructionKt.PushVariableInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.PushVariableInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PushVariableInstruction`
   */
  public object PushVariableInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PushVariableInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PushVariableInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PushVariableInstruction = _builder.build()

      /**
       * ```
       * The name of the variable whose value should be pushed onto the stack.
       * ```
       *
       * `string variableName = 1;`
       */
      public var variableName: kotlin.String
        @kotlin.jvm.JvmName("getVariableName")
          get() = _builder.variableName
        @kotlin.jvm.JvmName("setVariableName")
          set(value) {
          _builder.variableName = value
        }
      /**
       * ```
       * The name of the variable whose value should be pushed onto the stack.
       * ```
       *
       * `string variableName = 1;`
       */
      public fun clearVariableName() {
        _builder.clearVariableName()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializestoreVariableInstruction")
  public inline fun storeVariableInstruction(block: Yarn.InstructionKt.StoreVariableInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.StoreVariableInstruction =
    Yarn.InstructionKt.StoreVariableInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.StoreVariableInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.StoreVariableInstruction`
   */
  public object StoreVariableInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.StoreVariableInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.StoreVariableInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.StoreVariableInstruction = _builder.build()

      /**
       * ```
       * The name of the variable whose value should be updated with the value
       * currently on top of the stack.
       * ```
       *
       * `string variableName = 1;`
       */
      public var variableName: kotlin.String
        @kotlin.jvm.JvmName("getVariableName")
          get() = _builder.variableName
        @kotlin.jvm.JvmName("setVariableName")
          set(value) {
          _builder.variableName = value
        }
      /**
       * ```
       * The name of the variable whose value should be updated with the value
       * currently on top of the stack.
       * ```
       *
       * `string variableName = 1;`
       */
      public fun clearVariableName() {
        _builder.clearVariableName()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializestopInstruction")
  public inline fun stopInstruction(block: Yarn.InstructionKt.StopInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.StopInstruction =
    Yarn.InstructionKt.StopInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.StopInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.StopInstruction`
   */
  public object StopInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.StopInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.StopInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.StopInstruction = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializerunNodeInstruction")
  public inline fun runNodeInstruction(block: Yarn.InstructionKt.RunNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.RunNodeInstruction =
    Yarn.InstructionKt.RunNodeInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.RunNodeInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.RunNodeInstruction`
   */
  public object RunNodeInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.RunNodeInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.RunNodeInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.RunNodeInstruction = _builder.build()

      /**
       * ```
       * The name of the node to begin running.
       * ```
       *
       * `string nodeName = 1;`
       */
      public var nodeName: kotlin.String
        @kotlin.jvm.JvmName("getNodeName")
          get() = _builder.nodeName
        @kotlin.jvm.JvmName("setNodeName")
          set(value) {
          _builder.nodeName = value
        }
      /**
       * ```
       * The name of the node to begin running.
       * ```
       *
       * `string nodeName = 1;`
       */
      public fun clearNodeName() {
        _builder.clearNodeName()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializedetourToNodeInstruction")
  public inline fun detourToNodeInstruction(block: Yarn.InstructionKt.DetourToNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.DetourToNodeInstruction =
    Yarn.InstructionKt.DetourToNodeInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.DetourToNodeInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.DetourToNodeInstruction`
   */
  public object DetourToNodeInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.DetourToNodeInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.DetourToNodeInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.DetourToNodeInstruction = _builder.build()

      /**
       * `string nodeName = 1;`
       */
      public var nodeName: kotlin.String
        @kotlin.jvm.JvmName("getNodeName")
          get() = _builder.nodeName
        @kotlin.jvm.JvmName("setNodeName")
          set(value) {
          _builder.nodeName = value
        }
      /**
       * `string nodeName = 1;`
       */
      public fun clearNodeName() {
        _builder.clearNodeName()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializepeekAndDetourToNode")
  public inline fun peekAndDetourToNode(block: Yarn.InstructionKt.PeekAndDetourToNodeKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PeekAndDetourToNode =
    Yarn.InstructionKt.PeekAndDetourToNodeKt.Dsl._create(Yarn.YarnSpinner.Instruction.PeekAndDetourToNode.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.PeekAndDetourToNode`
   */
  public object PeekAndDetourToNodeKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.PeekAndDetourToNode.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.PeekAndDetourToNode.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.PeekAndDetourToNode = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializereturnInstruction")
  public inline fun returnInstruction(block: Yarn.InstructionKt.ReturnInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.ReturnInstruction =
    Yarn.InstructionKt.ReturnInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.ReturnInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.ReturnInstruction`
   */
  public object ReturnInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.ReturnInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.ReturnInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.ReturnInstruction = _builder.build()
    }
  }
  @kotlin.jvm.JvmName("-initializeaddSaliencyCandidateInstruction")
  public inline fun addSaliencyCandidateInstruction(block: Yarn.InstructionKt.AddSaliencyCandidateInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction =
    Yarn.InstructionKt.AddSaliencyCandidateInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.AddSaliencyCandidateInstruction`
   */
  public object AddSaliencyCandidateInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction = _builder.build()

      /**
       * ```
       * The unique ID for this piece of content, such as a line ID.
       * ```
       *
       * `string contentID = 1;`
       */
      public var contentID: kotlin.String
        @kotlin.jvm.JvmName("getContentID")
          get() = _builder.contentID
        @kotlin.jvm.JvmName("setContentID")
          set(value) {
          _builder.contentID = value
        }
      /**
       * ```
       * The unique ID for this piece of content, such as a line ID.
       * ```
       *
       * `string contentID = 1;`
       */
      public fun clearContentID() {
        _builder.clearContentID()
      }

      /**
       * ```
       * The complexity score of the candidate.
       * ```
       *
       * `int32 complexityScore = 2;`
       */
      public var complexityScore: kotlin.Int
        @kotlin.jvm.JvmName("getComplexityScore")
          get() = _builder.complexityScore
        @kotlin.jvm.JvmName("setComplexityScore")
          set(value) {
          _builder.complexityScore = value
        }
      /**
       * ```
       * The complexity score of the candidate.
       * ```
       *
       * `int32 complexityScore = 2;`
       */
      public fun clearComplexityScore() {
        _builder.clearComplexityScore()
      }

      /**
       * ```
       * The instruction number in the current node to jump to if this
       * candidate is selected.
       * ```
       *
       * `int32 destination = 3;`
       */
      public var destination: kotlin.Int
        @kotlin.jvm.JvmName("getDestination")
          get() = _builder.destination
        @kotlin.jvm.JvmName("setDestination")
          set(value) {
          _builder.destination = value
        }
      /**
       * ```
       * The instruction number in the current node to jump to if this
       * candidate is selected.
       * ```
       *
       * `int32 destination = 3;`
       */
      public fun clearDestination() {
        _builder.clearDestination()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeaddSaliencyCandidateFromNodeInstruction")
  public inline fun addSaliencyCandidateFromNodeInstruction(block: Yarn.InstructionKt.AddSaliencyCandidateFromNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction =
    Yarn.InstructionKt.AddSaliencyCandidateFromNodeInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.AddSaliencyCandidateFromNodeInstruction`
   */
  public object AddSaliencyCandidateFromNodeInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction = _builder.build()

      /**
       * ```
       * The name of the node to get saliency information from.
       * ```
       *
       * `string nodeName = 1;`
       */
      public var nodeName: kotlin.String
        @kotlin.jvm.JvmName("getNodeName")
          get() = _builder.nodeName
        @kotlin.jvm.JvmName("setNodeName")
          set(value) {
          _builder.nodeName = value
        }
      /**
       * ```
       * The name of the node to get saliency information from.
       * ```
       *
       * `string nodeName = 1;`
       */
      public fun clearNodeName() {
        _builder.clearNodeName()
      }

      /**
       * ```
       * The instruction number in the current node to jump to if this
       * candidate is selected.
       * ```
       *
       * `int32 destination = 2;`
       */
      public var destination: kotlin.Int
        @kotlin.jvm.JvmName("getDestination")
          get() = _builder.destination
        @kotlin.jvm.JvmName("setDestination")
          set(value) {
          _builder.destination = value
        }
      /**
       * ```
       * The instruction number in the current node to jump to if this
       * candidate is selected.
       * ```
       *
       * `int32 destination = 2;`
       */
      public fun clearDestination() {
        _builder.clearDestination()
      }
    }
  }
  @kotlin.jvm.JvmName("-initializeselectSaliencyCandidateInstruction")
  public inline fun selectSaliencyCandidateInstruction(block: Yarn.InstructionKt.SelectSaliencyCandidateInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction =
    Yarn.InstructionKt.SelectSaliencyCandidateInstructionKt.Dsl._create(Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `Yarn.Instruction.SelectSaliencyCandidateInstruction`
   */
  public object SelectSaliencyCandidateInstructionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
        internal fun _create(builder: Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
      internal fun _build(): Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction = _builder.build()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.copy(block: `Yarn`.InstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction =
  `Yarn`.InstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction.copy(block: `Yarn`.InstructionKt.PeekAndJumpInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction =
  `Yarn`.InstructionKt.PeekAndJumpInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction.copy(block: `Yarn`.InstructionKt.PeekAndRunNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction =
  `Yarn`.InstructionKt.PeekAndRunNodeInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.ShowOptionsInstruction.copy(block: `Yarn`.InstructionKt.ShowOptionsInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.ShowOptionsInstruction =
  `Yarn`.InstructionKt.ShowOptionsInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PushStringInstruction.copy(block: `Yarn`.InstructionKt.PushStringInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushStringInstruction =
  `Yarn`.InstructionKt.PushStringInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PushFloatInstruction.copy(block: `Yarn`.InstructionKt.PushFloatInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushFloatInstruction =
  `Yarn`.InstructionKt.PushFloatInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PushBoolInstruction.copy(block: `Yarn`.InstructionKt.PushBoolInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushBoolInstruction =
  `Yarn`.InstructionKt.PushBoolInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.JumpToInstruction.copy(block: `Yarn`.InstructionKt.JumpToInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.JumpToInstruction =
  `Yarn`.InstructionKt.JumpToInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.RunLineInstruction.copy(block: `Yarn`.InstructionKt.RunLineInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.RunLineInstruction =
  `Yarn`.InstructionKt.RunLineInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.RunCommandInstruction.copy(block: `Yarn`.InstructionKt.RunCommandInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.RunCommandInstruction =
  `Yarn`.InstructionKt.RunCommandInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.AddOptionInstruction.copy(block: `Yarn`.InstructionKt.AddOptionInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.AddOptionInstruction =
  `Yarn`.InstructionKt.AddOptionInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction.copy(block: `Yarn`.InstructionKt.JumpIfFalseInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction =
  `Yarn`.InstructionKt.JumpIfFalseInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PopInstruction.copy(block: `Yarn`.InstructionKt.PopInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PopInstruction =
  `Yarn`.InstructionKt.PopInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.CallFunctionInstruction.copy(block: `Yarn`.InstructionKt.CallFunctionInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.CallFunctionInstruction =
  `Yarn`.InstructionKt.CallFunctionInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PushVariableInstruction.copy(block: `Yarn`.InstructionKt.PushVariableInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PushVariableInstruction =
  `Yarn`.InstructionKt.PushVariableInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.StoreVariableInstruction.copy(block: `Yarn`.InstructionKt.StoreVariableInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.StoreVariableInstruction =
  `Yarn`.InstructionKt.StoreVariableInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.StopInstruction.copy(block: `Yarn`.InstructionKt.StopInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.StopInstruction =
  `Yarn`.InstructionKt.StopInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.RunNodeInstruction.copy(block: `Yarn`.InstructionKt.RunNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.RunNodeInstruction =
  `Yarn`.InstructionKt.RunNodeInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.DetourToNodeInstruction.copy(block: `Yarn`.InstructionKt.DetourToNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.DetourToNodeInstruction =
  `Yarn`.InstructionKt.DetourToNodeInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.PeekAndDetourToNode.copy(block: `Yarn`.InstructionKt.PeekAndDetourToNodeKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.PeekAndDetourToNode =
  `Yarn`.InstructionKt.PeekAndDetourToNodeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.ReturnInstruction.copy(block: `Yarn`.InstructionKt.ReturnInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.ReturnInstruction =
  `Yarn`.InstructionKt.ReturnInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction.copy(block: `Yarn`.InstructionKt.AddSaliencyCandidateInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction =
  `Yarn`.InstructionKt.AddSaliencyCandidateInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction.copy(block: `Yarn`.InstructionKt.AddSaliencyCandidateFromNodeInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction =
  `Yarn`.InstructionKt.AddSaliencyCandidateFromNodeInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction.copy(block: `Yarn`.InstructionKt.SelectSaliencyCandidateInstructionKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction =
  `Yarn`.InstructionKt.SelectSaliencyCandidateInstructionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val Yarn.YarnSpinner.InstructionOrBuilder.jumpToOrNull: Yarn.YarnSpinner.Instruction.JumpToInstruction?
  get() = if (hasJumpTo()) getJumpTo() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.peekAndJumpOrNull: Yarn.YarnSpinner.Instruction.PeekAndJumpInstruction?
  get() = if (hasPeekAndJump()) getPeekAndJump() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.runLineOrNull: Yarn.YarnSpinner.Instruction.RunLineInstruction?
  get() = if (hasRunLine()) getRunLine() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.runCommandOrNull: Yarn.YarnSpinner.Instruction.RunCommandInstruction?
  get() = if (hasRunCommand()) getRunCommand() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.addOptionOrNull: Yarn.YarnSpinner.Instruction.AddOptionInstruction?
  get() = if (hasAddOption()) getAddOption() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.showOptionsOrNull: Yarn.YarnSpinner.Instruction.ShowOptionsInstruction?
  get() = if (hasShowOptions()) getShowOptions() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.pushStringOrNull: Yarn.YarnSpinner.Instruction.PushStringInstruction?
  get() = if (hasPushString()) getPushString() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.pushFloatOrNull: Yarn.YarnSpinner.Instruction.PushFloatInstruction?
  get() = if (hasPushFloat()) getPushFloat() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.pushBoolOrNull: Yarn.YarnSpinner.Instruction.PushBoolInstruction?
  get() = if (hasPushBool()) getPushBool() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.jumpIfFalseOrNull: Yarn.YarnSpinner.Instruction.JumpIfFalseInstruction?
  get() = if (hasJumpIfFalse()) getJumpIfFalse() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.popOrNull: Yarn.YarnSpinner.Instruction.PopInstruction?
  get() = if (hasPop()) getPop() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.callFuncOrNull: Yarn.YarnSpinner.Instruction.CallFunctionInstruction?
  get() = if (hasCallFunc()) getCallFunc() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.pushVariableOrNull: Yarn.YarnSpinner.Instruction.PushVariableInstruction?
  get() = if (hasPushVariable()) getPushVariable() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.storeVariableOrNull: Yarn.YarnSpinner.Instruction.StoreVariableInstruction?
  get() = if (hasStoreVariable()) getStoreVariable() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.stopOrNull: Yarn.YarnSpinner.Instruction.StopInstruction?
  get() = if (hasStop()) getStop() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.runNodeOrNull: Yarn.YarnSpinner.Instruction.RunNodeInstruction?
  get() = if (hasRunNode()) getRunNode() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.peekAndRunNodeOrNull: Yarn.YarnSpinner.Instruction.PeekAndRunNodeInstruction?
  get() = if (hasPeekAndRunNode()) getPeekAndRunNode() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.detourToNodeOrNull: Yarn.YarnSpinner.Instruction.DetourToNodeInstruction?
  get() = if (hasDetourToNode()) getDetourToNode() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.peekAndDetourToNodeOrNull: Yarn.YarnSpinner.Instruction.PeekAndDetourToNode?
  get() = if (hasPeekAndDetourToNode()) getPeekAndDetourToNode() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.returnOrNull: Yarn.YarnSpinner.Instruction.ReturnInstruction?
  get() = if (hasReturn()) getReturn() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.addSaliencyCandidateOrNull: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateInstruction?
  get() = if (hasAddSaliencyCandidate()) getAddSaliencyCandidate() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.addSaliencyCandidateFromNodeOrNull: Yarn.YarnSpinner.Instruction.AddSaliencyCandidateFromNodeInstruction?
  get() = if (hasAddSaliencyCandidateFromNode()) getAddSaliencyCandidateFromNode() else null

public val Yarn.YarnSpinner.InstructionOrBuilder.selectSaliencyCandidateOrNull: Yarn.YarnSpinner.Instruction.SelectSaliencyCandidateInstruction?
  get() = if (hasSelectSaliencyCandidate()) getSelectSaliencyCandidate() else null

