// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yarn_spinner.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package Yarn;

@kotlin.jvm.JvmName("-initializenode")
public inline fun node(block: Yarn.NodeKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Node =
  Yarn.NodeKt.Dsl._create(Yarn.YarnSpinner.Node.newBuilder()).apply { block() }._build()
/**
 * ```
 * A collection of instructions
 * ```
 *
 * Protobuf type `Yarn.Node`
 */
public object NodeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Yarn.YarnSpinner.Node.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Yarn.YarnSpinner.Node.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Yarn.YarnSpinner.Node = _builder.build()

    /**
     * ```
     * The name of this node.
     * ```
     *
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * The name of this node.
     * ```
     *
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InstructionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     */
     public val instructions: com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.instructionsList
      )
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     * @param value The instructions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addInstructions")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>.add(value: Yarn.YarnSpinner.Instruction) {
      _builder.addInstructions(value)
    }
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     * @param value The instructions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignInstructions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>.plusAssign(value: Yarn.YarnSpinner.Instruction) {
      add(value)
    }
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     * @param values The instructions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllInstructions")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>.addAll(values: kotlin.collections.Iterable<Yarn.YarnSpinner.Instruction>) {
      _builder.addAllInstructions(values)
    }
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     * @param values The instructions to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllInstructions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>.plusAssign(values: kotlin.collections.Iterable<Yarn.YarnSpinner.Instruction>) {
      addAll(values)
    }
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     * @param index The index to set the value at.
     * @param value The instructions to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setInstructions")
    public operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>.set(index: kotlin.Int, value: Yarn.YarnSpinner.Instruction) {
      _builder.setInstructions(index, value)
    }
    /**
     * ```
     * The list of instructions in this node.
     * ```
     *
     * `repeated .Yarn.Instruction instructions = 7;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearInstructions")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Instruction, InstructionsProxy>.clear() {
      _builder.clearInstructions()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class HeadersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     */
     public val headers: com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.headersList
      )
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     * @param value The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addHeaders")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>.add(value: Yarn.YarnSpinner.Header) {
      _builder.addHeaders(value)
    }
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     * @param value The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>.plusAssign(value: Yarn.YarnSpinner.Header) {
      add(value)
    }
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     * @param values The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllHeaders")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>.addAll(values: kotlin.collections.Iterable<Yarn.YarnSpinner.Header>) {
      _builder.addAllHeaders(values)
    }
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     * @param values The headers to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllHeaders")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>.plusAssign(values: kotlin.collections.Iterable<Yarn.YarnSpinner.Header>) {
      addAll(values)
    }
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     * @param index The index to set the value at.
     * @param value The headers to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setHeaders")
    public operator fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>.set(index: kotlin.Int, value: Yarn.YarnSpinner.Header) {
      _builder.setHeaders(index, value)
    }
    /**
     * ```
     * The headers present on this node.
     * ```
     *
     * `repeated .Yarn.Header headers = 6;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearHeaders")
    public fun com.google.protobuf.kotlin.DslList<Yarn.YarnSpinner.Header, HeadersProxy>.clear() {
      _builder.clearHeaders()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Node.copy(block: `Yarn`.NodeKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Node =
  `Yarn`.NodeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

