// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yarn_spinner.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package Yarn;

@kotlin.jvm.JvmName("-initializeoperand")
public inline fun operand(block: Yarn.OperandKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Operand =
  Yarn.OperandKt.Dsl._create(Yarn.YarnSpinner.Operand.newBuilder()).apply { block() }._build()
/**
 * ```
 * A value used by an Instruction.
 * ```
 *
 * Protobuf type `Yarn.Operand`
 */
public object OperandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Yarn.YarnSpinner.Operand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Yarn.YarnSpinner.Operand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Yarn.YarnSpinner.Operand = _builder.build()

    /**
     * ```
     * A string.
     * ```
     *
     * `string string_value = 1;`
     */
    public var stringValue: kotlin.String
      @kotlin.jvm.JvmName("getStringValue")
        get() = _builder.stringValue
      @kotlin.jvm.JvmName("setStringValue")
        set(value) {
        _builder.stringValue = value
      }
    /**
     * ```
     * A string.
     * ```
     *
     * `string string_value = 1;`
     */
    public fun clearStringValue() {
      _builder.clearStringValue()
    }
    /**
     * ```
     * A string.
     * ```
     *
     * `string string_value = 1;`
     * @return Whether the stringValue field is set.
     */
    public fun hasStringValue(): kotlin.Boolean {
      return _builder.hasStringValue()
    }

    /**
     * ```
     * A boolean (true or false).
     * ```
     *
     * `bool bool_value = 2;`
     */
    public var boolValue: kotlin.Boolean
      @kotlin.jvm.JvmName("getBoolValue")
        get() = _builder.boolValue
      @kotlin.jvm.JvmName("setBoolValue")
        set(value) {
        _builder.boolValue = value
      }
    /**
     * ```
     * A boolean (true or false).
     * ```
     *
     * `bool bool_value = 2;`
     */
    public fun clearBoolValue() {
      _builder.clearBoolValue()
    }
    /**
     * ```
     * A boolean (true or false).
     * ```
     *
     * `bool bool_value = 2;`
     * @return Whether the boolValue field is set.
     */
    public fun hasBoolValue(): kotlin.Boolean {
      return _builder.hasBoolValue()
    }

    /**
     * ```
     * A floating point number.
     * ```
     *
     * `float float_value = 3;`
     */
    public var floatValue: kotlin.Float
      @kotlin.jvm.JvmName("getFloatValue")
        get() = _builder.floatValue
      @kotlin.jvm.JvmName("setFloatValue")
        set(value) {
        _builder.floatValue = value
      }
    /**
     * ```
     * A floating point number.
     * ```
     *
     * `float float_value = 3;`
     */
    public fun clearFloatValue() {
      _builder.clearFloatValue()
    }
    /**
     * ```
     * A floating point number.
     * ```
     *
     * `float float_value = 3;`
     * @return Whether the floatValue field is set.
     */
    public fun hasFloatValue(): kotlin.Boolean {
      return _builder.hasFloatValue()
    }
    public val valueCase: Yarn.YarnSpinner.Operand.ValueCase
    @kotlin.jvm.JvmName("getValueCase")
      get() = _builder.getValueCase()

    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Operand.copy(block: `Yarn`.OperandKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Operand =
  `Yarn`.OperandKt.Dsl._create(this.toBuilder()).apply { block() }._build()

