// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yarn_spinner.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package Yarn;

@kotlin.jvm.JvmName("-initializeprogram")
public inline fun program(block: Yarn.ProgramKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Program =
  Yarn.ProgramKt.Dsl._create(Yarn.YarnSpinner.Program.newBuilder()).apply { block() }._build()
/**
 * ```
 * A complete Yarn program.
 * ```
 *
 * Protobuf type `Yarn.Program`
 */
public object ProgramKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Yarn.YarnSpinner.Program.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: Yarn.YarnSpinner.Program.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): Yarn.YarnSpinner.Program = _builder.build()

    /**
     * ```
     * The name of the program.
     * ```
     *
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * ```
     * The name of the program.
     * ```
     *
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NodesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The collection of nodes in this program.
     * ```
     *
     * `map<string, .Yarn.Node> nodes = 2;`
     */
     public val nodes: com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Node, NodesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getNodesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.nodesMap
      )
    /**
     * ```
     * The collection of nodes in this program.
     * ```
     *
     * `map<string, .Yarn.Node> nodes = 2;`
     */
    @kotlin.jvm.JvmName("putNodes")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Node, NodesProxy>
      .put(key: kotlin.String, value: Yarn.YarnSpinner.Node) {
         _builder.putNodes(key, value)
       }
    /**
     * ```
     * The collection of nodes in this program.
     * ```
     *
     * `map<string, .Yarn.Node> nodes = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setNodes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Node, NodesProxy>
      .set(key: kotlin.String, value: Yarn.YarnSpinner.Node) {
         put(key, value)
       }
    /**
     * ```
     * The collection of nodes in this program.
     * ```
     *
     * `map<string, .Yarn.Node> nodes = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeNodes")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Node, NodesProxy>
      .remove(key: kotlin.String) {
         _builder.removeNodes(key)
       }
    /**
     * ```
     * The collection of nodes in this program.
     * ```
     *
     * `map<string, .Yarn.Node> nodes = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllNodes")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Node, NodesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, Yarn.YarnSpinner.Node>) {
         _builder.putAllNodes(map)
       }
    /**
     * ```
     * The collection of nodes in this program.
     * ```
     *
     * `map<string, .Yarn.Node> nodes = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearNodes")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Node, NodesProxy>
      .clear() {
         _builder.clearNodes()
       }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class InitialValuesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * The collection of initial values for variables; if a PUSH_VARIABLE
     * instruction is run, and the value is not found in the storage, this
     * value will be used
     * ```
     *
     * `map<string, .Yarn.Operand> initial_values = 3;`
     */
     public val initialValues: com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Operand, InitialValuesProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getInitialValuesMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.initialValuesMap
      )
    /**
     * ```
     * The collection of initial values for variables; if a PUSH_VARIABLE
     * instruction is run, and the value is not found in the storage, this
     * value will be used
     * ```
     *
     * `map<string, .Yarn.Operand> initial_values = 3;`
     */
    @kotlin.jvm.JvmName("putInitialValues")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Operand, InitialValuesProxy>
      .put(key: kotlin.String, value: Yarn.YarnSpinner.Operand) {
         _builder.putInitialValues(key, value)
       }
    /**
     * ```
     * The collection of initial values for variables; if a PUSH_VARIABLE
     * instruction is run, and the value is not found in the storage, this
     * value will be used
     * ```
     *
     * `map<string, .Yarn.Operand> initial_values = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setInitialValues")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Operand, InitialValuesProxy>
      .set(key: kotlin.String, value: Yarn.YarnSpinner.Operand) {
         put(key, value)
       }
    /**
     * ```
     * The collection of initial values for variables; if a PUSH_VARIABLE
     * instruction is run, and the value is not found in the storage, this
     * value will be used
     * ```
     *
     * `map<string, .Yarn.Operand> initial_values = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeInitialValues")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Operand, InitialValuesProxy>
      .remove(key: kotlin.String) {
         _builder.removeInitialValues(key)
       }
    /**
     * ```
     * The collection of initial values for variables; if a PUSH_VARIABLE
     * instruction is run, and the value is not found in the storage, this
     * value will be used
     * ```
     *
     * `map<string, .Yarn.Operand> initial_values = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllInitialValues")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Operand, InitialValuesProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, Yarn.YarnSpinner.Operand>) {
         _builder.putAllInitialValues(map)
       }
    /**
     * ```
     * The collection of initial values for variables; if a PUSH_VARIABLE
     * instruction is run, and the value is not found in the storage, this
     * value will be used
     * ```
     *
     * `map<string, .Yarn.Operand> initial_values = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearInitialValues")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, Yarn.YarnSpinner.Operand, InitialValuesProxy>
      .clear() {
         _builder.clearInitialValues()
       }

    /**
     * ```
     * The version of the Yarn Spinner language that this program was compiled under.
     * ```
     *
     * `int32 language_version = 4;`
     */
    public var languageVersion: kotlin.Int
      @kotlin.jvm.JvmName("getLanguageVersion")
        get() = _builder.languageVersion
      @kotlin.jvm.JvmName("setLanguageVersion")
        set(value) {
        _builder.languageVersion = value
      }
    /**
     * ```
     * The version of the Yarn Spinner language that this program was compiled under.
     * ```
     *
     * `int32 language_version = 4;`
     */
    public fun clearLanguageVersion() {
      _builder.clearLanguageVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Yarn.YarnSpinner.Program.copy(block: `Yarn`.ProgramKt.Dsl.() -> kotlin.Unit): Yarn.YarnSpinner.Program =
  `Yarn`.ProgramKt.Dsl._create(this.toBuilder()).apply { block() }._build()

